apiVersion: apps/v1
kind: Deployment
metadata:
  name: babianjing-deployment
  labels:
    app: babianjing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: babianjing
  template:
    metadata:
      labels:
        app: babianjing
    spec:
      containers:
        - name: babianjing
          image: babianjing:aae9a34
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: babianjing-service
spec:
  selector:
    app: babianjing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
