apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: default
  labels:
    app: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo-service
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          imagePullPolicy: Never
          ports:
            - name: mongo-port
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_PASS
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumeClaimTemplates:
        - metadata:
            name: mongo-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: default
  labels:
    app: mongo
spec:
  ports:
    - name: mongo-service-port
      port: 27017
      targetPort: mongo-port
  selector:
    app: mongo
